runtime: nodejs14
service: front-end
automatic_scaling:
  max_instances: 1
  max_idle_instances: 1
handlers:
  # Serve all static files with url ending with a file extension
  - url: /(.*\..+)$
    secure: always
    redirect_http_response_code: 301
    static_files: build/\1
    upload: build/(.*\..+)$
  # Catch all handlers to index.html
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    static_files: build/index.html
    upload: build/index.html
